language: cpp
sudo: required
dist: trusty
services:
  - docker
compiler:
  - clang
  - gcc
env:
  - BUILD_SPI_JAVASTUB=0
  - BUILD_SPI_JAVASTUB=1
  - BUILD_SPI_JAVASTUB=0 IQRF_APPS=iqrfapp
  - BUILD_SPI_JAVASTUB=1 IQRF_APPS=iqrfapp
  - BUILD_SPI_JAVASTUB=0 IQRF_APPS=iqrf_ide_dummy
  - BUILD_SPI_JAVASTUB=1 IQRF_APPS=iqrf_ide_dummy
matrix:
  allow_failures:
    - compiler: clang
before_install:
  - docker pull ubuntu:16.04
  - docker run --name travis-ci -v $TRAVIS_BUILD_DIR:/iqrfsdk -td ubuntu:16.04 /bin/bash
install:
  - docker exec travis-ci bash -c "apt-get update"
  - docker exec travis-ci bash -c "apt-get install -y build-essential cmake linux-libc-dev git libssl-dev"
  - if [[ "$CC" == "clang" ]]; then docker exec travis-ci bash -c "apt-get install -y clang"; fi
  - if [[ "$BUILD_SPI_JAVASTUB" == 1 ]]; then docker exec travis-ci bash -c "apt-get install -y default-jre default-jdk"; fi
script:
  - docker exec travis-ci bash -c "cd /iqrfsdk/scripts && CC=${CC} CXX=${CXX} bash build-travis.sh"
  - if [[ "$IQRF_APPS" == "iqrfapp" ]]; then docker exec travis-ci bash -c "cd /iqrfsdk/applications/iqrfapp && CC=${CC} CXX=${CXX} bash buildMake.sh"; fi
  - if [[ "$IQRF_APPS" == "iqrf_ide_dummy" ]]; then docker exec travis-ci bash -c "cd /iqrfsdk/applications/iqrf_ide_dummy && CC=${CC} CXX=${CXX} bash buildMake.sh"; fi
after_script:
  - docker stop travis-ci
